name: "Bug report / Mod update request"
about: "Report bugs or request updates to mods in the modpack"
title: "[BUG] / [UPDATE] - "
labels: ["bug", "enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Describe the issue or request
        Please clearly describe the bug you encountered or the mod update you are requesting.

  - type: textarea
    id: reproduction_steps
    attributes:
      label: "Steps to reproduce (for bugs)"
      description: "Please provide detailed steps so we can reproduce the issue."
      placeholder: |
        1.
        2.
        3.
    validations:
      required: false

  - type: textarea
    id: expected_behavior
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
      placeholder: "Describe what should have happened."
    validations:
      required: false

  - type: textarea
    id: actual_behavior
    attributes:
      label: "Actual behavior"
      description: "What actually happened?"
      placeholder: "Describe the actual outcome."
    validations:
      required: false

  - type: textarea
    id: logs_screenshots
    attributes:
      label: "Screenshots or logs (if applicable)"
      description: "Attach any relevant screenshots or logs to help illustrate the issue."
      placeholder: "Paste logs or add screenshot links here."
    validations:
      required: false

  - type: input
    id: modpack_version
    attributes:
      label: "Modpack version"
      description: "Which version of the modpack are you using?"
      placeholder: "e.g. 1.0.3"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: "Additional context"
      description: "Any other details or context about the issue or request."
      placeholder: "Add any other information here."
    validations:
      required: false
